data_material = {
    'customers': [
        {'name': 'тест для дебага', 'contacts_info': 'Телефон: (999) 999-99-99\nПочта: a@ma.aa'},
        {'name': 'пал дизайн', 'contacts_info': 'Телефон: (495) 782-33-32, 720-234-2\nПочта: 7823332@mail.ru'},
        {'name': 'печатный дом (прянишникова)', 'contacts_info': 'Телефон: (499) 976-44-89\nПочта: lvt2000@list.ru'},
    ],
    'product_stage_options': [
        {'id': 1, 'name': 'на просчёте'}, {'id': 2, 'name': 'согласование'}, {'id': 3, 'name': 'лазерный рез'},
        {'id': 4, 'name': 'забивка'}, {'id': 5, 'name': 'обклейка'}, {'id': 8, 'name': 'в производстве'},
        {'id': 7, 'name': 'готовность на производстве'}, {'id': 8, 'name': 'передано в Москву'},
        {'id': 9, 'name': 'ожидает заказчика на производстве'}, {'id': 10, 'name': 'ожидает заказчика в Москве'},
        {'id': 11, 'name': 'доставка'}, {'id': 12, 'name': 'завершён'}, {'id': 13, 'name': 'ремонт'},
        {'id': 14, 'name': 'штамп удалён'}
    ],
    'delivery_options': [
        {'id': 1, 'delivery_name': 'самовывоз с производства'}, {'id': 2, 'delivery_name': 'самовывоз из Москвы'},
        {'id': 3, 'delivery_name': 'доставка до т/к'}, {'id': 4, 'delivery_name': 'достависта'},
        {'id': 4, 'delivery_name': 'доставка с Производства'}, {'id': 5, 'delivery_name': 'доставка из Москвы'},
        {'id': 6, 'delivery_name': 'нет информации'},
    ],
    'positions': [
        {'id': 1, 'position_name': 'директор'}, {'id': 2, 'position_name': 'администратор'},
        {'id': 3, 'position_name': 'менеджер'}, {'id': 4, 'position_name': 'конструктор'},
        {'id': 4, 'position_name': 'бухгалтер'}, {'id': 5, 'position_name': 'производство'},
    ],
    'employees': [
        {'id': 1, 'surname': 'testov', 'name': 'test', 'patronymic': 'testovich', 'birthday': '01.01.1990',
         'position': 4},
    ],
    'material_types': [
        {'id': 1, 'material_type': 'фанера'}, {'id': 2, 'material_type': 'биговальные ножи'},
        {'id': 3, 'material_type': 'режущие ножи'}, {'id': 4, 'material_type': 'перфорационные ножи'},
        {'id': 5, 'material_type': 'комбинированные ножи'}, {'id': 6, 'material_type': 'пробойники'},
        {'id': 7, 'material_type': 'резина'}, {'id': 8, 'material_type': 'другие ножи'},
        {'id': 9, 'material_type': 'другое'},
    ],
    'materials': [
        {'id': 1, 'material_type': 1, 'material_name': 'фанера 2/2 6мм'},
        {'id': 2, 'material_type': 1, 'material_name': 'фанера 2/2 10мм'},
        {'id': 3, 'material_type': 1, 'material_name': 'фанера 2/2 15мм'},
        {'id': 4, 'material_type': 1, 'material_name': 'фанера 2/2 18мм'},
        {'id': 5, 'material_type': 2, 'material_name': 'биговка pss 2пт 22,9'},
        {'id': 6, 'material_type': 2, 'material_name': 'биговка pss 2пт 23,0'},
        {'id': 7, 'material_type': 2, 'material_name': 'биговка pss 2пт 23,1'},
        {'id': 8, 'material_type': 2, 'material_name': 'биговка pss 2пт 23,15'},
        {'id': 9, 'material_type': 2, 'material_name': 'биговка pss 2пт 23,2'},
        {'id': 10, 'material_type': 2, 'material_name': 'биговка pss 2пт 23,25'},
        {'id': 11, 'material_type': 2, 'material_name': 'биговка pss 2пт 23,3'},
        {'id': 12, 'material_type': 2, 'material_name': 'биговка pss 2пт 23,35'},
        {'id': 13, 'material_type': 2, 'material_name': 'биговка pss 2пт 23,4'},
        {'id': 14, 'material_type': 2, 'material_name': 'биговка pss 2пт 23,45'},
        {'id': 15, 'material_type': 2, 'material_name': 'биговка pss 2пт 23,5'},
        {'id': 16, 'material_type': 2, 'material_name': 'биговка pss 2пт 23,6'},
        {'id': 17, 'material_type': 2, 'material_name': 'биговка pss 3пт 20,5'},
        {'id': 18, 'material_type': 2, 'material_name': 'биговка pss 3пт 21,5'},
        {'id': 19, 'material_type': 2, 'material_name': 'биговка pss 3пт 22,0'},
        {'id': 20, 'material_type': 2, 'material_name': 'биговка pss 3пт 22,1'},
        {'id': 21, 'material_type': 2, 'material_name': 'биговка pss 3пт 22,4'},
        {'id': 22, 'material_type': 2, 'material_name': 'биговка pss 3пт 22,5'},
        {'id': 23, 'material_type': 2, 'material_name': 'биговка pss 3пт 22,6'},
        {'id': 24, 'material_type': 2, 'material_name': 'биговка pss 3пт 22,7'},
        {'id': 25, 'material_type': 2, 'material_name': 'биговка pss 3пт 22,75'},
        {'id': 26, 'material_type': 2, 'material_name': 'биговка pss 3пт 22,8'},
        {'id': 27, 'material_type': 2, 'material_name': 'биговка pss 3пт 22,9'},
        {'id': 28, 'material_type': 2, 'material_name': 'биговка pss 3пт 23,0'},
        {'id': 29, 'material_type': 2, 'material_name': 'биговка pss 3пт 23,1'},
        {'id': 30, 'material_type': 2, 'material_name': 'биговка pss 3пт 23,2'},
        {'id': 31, 'material_type': 3, 'material_name': 'режущие pss 2пт 23,8 А'},
        {'id': 32, 'material_type': 3, 'material_name': 'режущие pss 2пт 23,8 АА'},
        {'id': 33, 'material_type': 3, 'material_name': 'режущие pss 3пт 23,8 А'},
        {'id': 34, 'material_type': 3, 'material_name': 'режущие pss 3пт 23,8 АА'},
        {'id': 35, 'material_type': 4, 'material_name': 'перфорация pss 2пт 1/1 23,8'},
        {'id': 36, 'material_type': 4, 'material_name': 'перфорация pss 2пт 2/2 23,8'},
        {'id': 37, 'material_type': 4, 'material_name': 'перфорация pss 2пт 3/1 23,8'},
        {'id': 38, 'material_type': 4, 'material_name': 'перфорация pss 2пт 3/3 23,8'},
        {'id': 39, 'material_type': 4, 'material_name': 'перфорация pss 2пт 4/4 23,8'},
        {'id': 40, 'material_type': 4, 'material_name': 'перфорация pss 2пт 5/5 23,8'},
        {'id': 41, 'material_type': 4, 'material_name': 'перфорация pss 2пт 6/6 23,8'},
        {'id': 42, 'material_type': 4, 'material_name': 'перфорация pss 2пт 7/7 23,8'},
        {'id': 43, 'material_type': 4, 'material_name': 'перфорация pss 3пт 5/5 23,8'},
        {'id': 43, 'material_type': 4, 'material_name': 'перфорация pss 3пт 6/6 23,8'},
        {'id': 43, 'material_type': 4, 'material_name': 'перфорация pss 3пт 7/7 23,8'},
        {'id': 43, 'material_type': 4, 'material_name': 'перфорация pss 3пт 10/10 23,8'},
        {'id': 44, 'material_type': 5, 'material_name': 'комби pss 3пт 23,8/22,7 10/10'},
        {'id': 45, 'material_type': 5, 'material_name': 'комби pss 3пт 23,8/22,7 15/15'},
    ],
}
