data_material = {
    'customers': [
        {'name': 'ТЕСТ ДЛЯ ДЕБАГА', 'contacts_info': 'Телефон: (999) 999-99-99\nПочта: a@ma.aa'},
        {'name': 'ПАЛ ДИЗАЙН', 'contacts_info': 'Телефон: (495) 782-33-32, 720-234-2\nПочта: 7823332@mail.ru'},
        {'name': 'ПЕЧАТНЫЙ ДОМ (Прянишникова)', 'contacts_info': 'Телефон: (499) 976-44-89\nПочта: lvt2000@list.ru'},
    ],
    'product_stage_options': [
        {'id': 1, 'name': 'На просчёте'}, {'id': 2, 'name': 'Согласование'}, {'id': 3, 'name': 'Лазерный рез'},
        {'id': 4, 'name': 'Забивка'}, {'id': 5, 'name': 'Обклейка'}, {'id': 8, 'name': 'В производстве'},
        {'id': 7, 'name': 'Готовность на производстве'}, {'id': 8, 'name': 'Передано в Москву'},
        {'id': 9, 'name': 'Ожидает заказчика на производстве'}, {'id': 10, 'name': 'Ожидает заказчика в Москве'},
        {'id': 11, 'name': 'Доставка'}, {'id': 12, 'name': 'Завершён'}, {'id': 13, 'name': 'Ремонт'},
        {'id': 14, 'name': 'Штамп удалён'}
    ],
    'delivery_options': [
        {'id': 1, 'delivery_name': 'Самовывоз с производства'}, {'id': 2, 'delivery_name': 'Самовывоз из Москвы'},
        {'id': 3, 'delivery_name': 'Доставка до т/к'}, {'id': 4, 'delivery_name': 'Достависта'},
        {'id': 4, 'delivery_name': 'Доставка с Производства'}, {'id': 5, 'delivery_name': 'Доставка из Москвы'},
        {'id': 6, 'delivery_name': 'Нет информации'},
    ],
    'positions': [
        {'id': 1, 'position_name': 'Директор'}, {'id': 2, 'position_name': 'Администратор'},
        {'id': 3, 'position_name': 'Менеджер'}, {'id': 4, 'position_name': 'Конструктор'},
        {'id': 4, 'position_name': 'Бухгалтер'}, {'id': 5, 'position_name': 'Производство'},
    ],
    'employees': [
        {'id': 1, 'surname': 'Testov', 'name': 'Test', 'patronymic': 'Testovich', 'birthday': '01.01.1990',
         'position': 4},
    ],
    'material_types': [
        {'id': 1, 'material_type': 'Фанера'}, {'id': 2, 'material_type': 'Биговальные ножи'},
        {'id': 3, 'material_type': 'Режущие ножи'}, {'id': 4, 'material_type': 'Перфорационные ножи'},
        {'id': 5, 'material_type': 'Комбинированные ножи'}, {'id': 6, 'material_type': 'Пробойники'},
        {'id': 7, 'material_type': 'Резина'}, {'id': 8, 'material_type': 'Другие ножи'},
        {'id': 9, 'material_type': 'Другое'},
    ],
    'materials': [
        {'id': 1, 'material_type': 1, 'material_name': 'Фанера 2/2 6мм'},
        {'id': 2, 'material_type': 1, 'material_name': 'Фанера 2/2 10мм'},
        {'id': 3, 'material_type': 1, 'material_name': 'Фанера 2/2 15мм'},
        {'id': 4, 'material_type': 1, 'material_name': 'Фанера 2/2 18мм'},
        {'id': 5, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 22,9'},
        {'id': 6, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 23,0'},
        {'id': 7, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 23,1'},
        {'id': 8, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 23,15'},
        {'id': 9, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 23,2'},
        {'id': 10, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 23,25'},
        {'id': 11, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 23,3'},
        {'id': 12, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 23,35'},
        {'id': 13, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 23,4'},
        {'id': 14, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 23,45'},
        {'id': 15, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 23,5'},
        {'id': 16, 'material_type': 2, 'material_name': 'Биговка PSS 2пт 23,6'},
        {'id': 17, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 20,5'},
        {'id': 18, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 21,5'},
        {'id': 19, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 22,0'},
        {'id': 20, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 22,1'},
        {'id': 21, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 22,4'},
        {'id': 22, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 22,5'},
        {'id': 23, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 22,6'},
        {'id': 24, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 22,7'},
        {'id': 25, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 22,75'},
        {'id': 26, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 22,8'},
        {'id': 27, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 22,9'},
        {'id': 28, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 23,0'},
        {'id': 29, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 23,1'},
        {'id': 30, 'material_type': 2, 'material_name': 'Биговка PSS 3пт 23,2'},
        {'id': 31, 'material_type': 3, 'material_name': 'Режущие PSS 2пт 23,8 А'},
        {'id': 32, 'material_type': 3, 'material_name': 'Режущие PSS 2пт 23,8 АА'},
        {'id': 33, 'material_type': 3, 'material_name': 'Режущие PSS 3пт 23,8 А'},
        {'id': 34, 'material_type': 3, 'material_name': 'Режущие PSS 3пт 23,8 АА'},
        {'id': 35, 'material_type': 4, 'material_name': 'Перфорация PSS 2пт 1/1 23,8'},
        {'id': 36, 'material_type': 4, 'material_name': 'Перфорация PSS 2пт 2/2 23,8'},
        {'id': 37, 'material_type': 4, 'material_name': 'Перфорация PSS 2пт 3/1 23,8'},
        {'id': 38, 'material_type': 4, 'material_name': 'Перфорация PSS 2пт 3/3 23,8'},
        {'id': 39, 'material_type': 4, 'material_name': 'Перфорация PSS 2пт 4/4 23,8'},
        {'id': 40, 'material_type': 4, 'material_name': 'Перфорация PSS 2пт 5/5 23,8'},
        {'id': 41, 'material_type': 4, 'material_name': 'Перфорация PSS 2пт 6/6 23,8'},
        {'id': 42, 'material_type': 4, 'material_name': 'Перфорация PSS 2пт 7/7 23,8'},
        {'id': 43, 'material_type': 4, 'material_name': 'Перфорация PSS 3пт 5/5 23,8'},
        {'id': 43, 'material_type': 4, 'material_name': 'Перфорация PSS 3пт 6/6 23,8'},
        {'id': 43, 'material_type': 4, 'material_name': 'Перфорация PSS 3пт 7/7 23,8'},
        {'id': 43, 'material_type': 4, 'material_name': 'Перфорация PSS 3пт 10/10 23,8'},
        {'id': 44, 'material_type': 5, 'material_name': 'Комби PSS 3пт 23,8/22,7 10/10'},
        {'id': 45, 'material_type': 5, 'material_name': 'Комби PSS 3пт 23,8/22,7 15/15'},
    ],
}
